### ISSUE TITLE
Websppon 8 error

### ISSUE THREAD

**Issue by uwegeercken** [HiromuHota/pentaho-kettle#86] opened 2017-11-18 16:49 UTC
I get following error when running the latest docker container in Firefox 57 and also in Chrome Version 62.0.3202.94 on Fedora 27:

This happend when I tried to open the Avro Input dialog.

Unable to open dialog for this step
java.lang.NoClassDefFoundError: org/eclipse/jface/window/DefaultToolTip
	at org.pentaho.big.data.kettle.plugins.formats.impl.avro.BaseAvroStepDialog.addColumnTooltip(BaseAvroStepDialog.java:568)
	at org.pentaho.big.data.kettle.plugins.formats.impl.avro.input.AvroInputDialog.addFieldsTab(AvroInputDialog.java:198)
	at org.pentaho.big.data.kettle.plugins.formats.impl.avro.input.AvroInputDialog.createAfterFile(AvroInputDialog.java:94)
	at org.pentaho.big.data.kettle.plugins.formats.impl.avro.BaseAvroStepDialog.createUI(BaseAvroStepDialog.java:176)
	at org.pentaho.big.data.kettle.plugins.formats.impl.avro.BaseAvroStepDialog.open(BaseAvroStepDialog.java:138)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:127)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8769)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3303)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:802)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:218)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

Cheers,

Uwe

**Comment by HiromuHota** [comment] 2017-11-20 17:34
Hi Uwe,

I was able to reproduce this issue. This issue happens also when opening Avro Output and Parquet Input/Output.
The root cause is that `org/eclipse/jface/window/DefaultToolTip` has not been implemented in RAP/RWT.
It is time to start implementing this.

**Comment by HiromuHota** [comment] 2017-11-20 19:27
Resolved by 1c965af3ec27b2ebcc3b4844186e8b9e05045956.
Please check a new Docker image of `nightly-full`.

**Closed by HiromuHota** 2017-11-20 19:27 UTC
