### ISSUE TITLE
migrate the custom plugins to webspoon

### ISSUE THREAD

**Issue by cmdares** [HiromuHota/pentaho-kettle#190] opened 2020-02-06 13:36 UTC
First of all, thank you for your attention https://github.com/HiromuHota/pentaho-kettle/issues/189
I did a comparative test.

1.dowload kettle-sdk-plugin-assembly-9.0.0.0-423.zip  from https://sourceforge.net/projects/pentaho/files

2.unzip and cd /kettle-sdk-plugin-assembly-9.0.0.0-423/kettle-sdk-step-plugin/
edit file pom.xml
`
add <profiles> ... </profiles>  like this...
`
`
<profiles>
    <profile>
      <id>pentaho</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>pentaho-public</id>
          <name>Pentaho Public</name>
          <url>http://nexus.pentaho.org/content/groups/omni</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>pentaho-public</id>
          <name>Pentaho Public</name>
          <url>http://nexus.pentaho.org/content/groups/omni</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
</profiles>
`
3.then exce "mvn package"
4.unzip kettle-sdk-step-plugin-9.0.0.0-423.zip  to data-integration/plugins/steps/
5.start  spoon.bat or spoon.sh the "demo step" plugin show up in the catalog and it's work.
pdi client looks like it's working!

???????How to deploy custom plugin to the webspoon???????

1.unzip kettle-sdk-step-plugin-9.0.0.0-423.zip  to apache-tomcat-8.5.50/plugins/steps/
2.restart the tomcat and retry the webui and there is no change in the catalog tree.
What's wrong? How to deploy the custom plugin to the webspoon.
if the plugin code should be rewrite with xul ?
Please give a simple guide for developing and deploying custom plugins.
You need to give a description of how to migrate the custom plugins of  kettle client to webspoon.
thansk!

**Comment by HiromuHota** [comment] 2020-02-06 17:15
This is actually a duplicate of #189. From webSpoon's point of view, it is the same if you add a custom plugin or if you migrate it from Spoon.

Having said, there is nothing wrong with the steps you described.
Just put your plugin under `$CATALINA_HOME/plugins` and restart the tomcat.

```
$CATALINA_HOME
├── plugins
│   ├── YourPlugin
│   │   └── YourPlugin.jar
```

Log files at `$CATALINA_HOME/logs/` might be useful to figure out what went wrong.

**Comment by cmdares** [comment] 2020-02-07 11:49
According to the above method, it has also been tested, but still can't.
It will take you a little time. Follow the above steps to test it yourself.
It doesn't work in my environment. There is no exception in Tomcat log.
For the first time, I don't know why.
this the demo plugin
[kettle-sdk-step-plugin-9.0.0.0-423.zip](https://github.com/HiromuHota/pentaho-kettle/files/4170668/kettle-sdk-step-plugin-9.0.0.0-423.zip)

DemoStepMeta  Part of code
`
@Step(
  id = "DemoStep",
  name = "DemoStep.Name",
  description = "DemoStep.TooltipDesc",
  image = "org/pentaho/di/sdk/samples/steps/demo/resources/demo.svg",
  categoryDescription = "i18n:org.pentaho.di.trans.step:BaseStep.Category.Transform",
  i18nPackageName = "org.pentaho.di.sdk.samples.steps.demo",
  documentationUrl = "DemoStep.DocumentationURL",
  casesUrl = "DemoStep.CasesURL",
  forumUrl = "DemoStep.ForumURL"
  )
@InjectionSupported( localizationPrefix = "DemoStepMeta.Injection." )
public class DemoStepMeta extends BaseStepMeta implements StepMetaInterface
`

**Comment by HiromuHota** [comment] 2020-02-07 17:22
I tested the plugin that you compiled and uploaded here with the Docker version (hiromuhota/webspoon:nightly, which is based on 9.0.0.0-R), and confirmed that it worked.

I wonder what's your environment. What's the webSpoon version?

**Comment by cmdares** [comment] 2020-02-07 19:20
0.8.3.20

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HiromuHota** [comment] 2020-02-07 19:22
Try kettle-sdk-plugin-assembly-8.3.0.0-371.zip instead of kettle-sdk-plugin-assembly-9.0.0.0-423.zip.

**Comment by cmdares** [comment] 2020-02-07 19:23
I'll take a look at the situation with the latest version test. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmdares** [comment] 2020-02-08 05:35
kettle-sdk-plugin-assembly-8.3.0.0-371.zip
+
webSpoon/0.8.3.20

this plugin install dir :   
/apache-tomcat-8.5.50/plugins/kettle-sdk-step-plugin/kettle-sdk-step-plugin-8.3.0.0-371.jar
Still not working.
faint.

**Comment by HiromuHota** [comment] 2020-02-10 17:08
How did you deploy webSpoon?
If you used the Docker image, the path should be `/usr/local/tomcat/plugins` of the Docker container (not the host machine).

**Comment by cmdares** [comment] 2020-02-11 08:37
general download install 
not docker

**Comment by cmdares** [comment] 2020-02-11 10:32
I tested it with docker and everything was ok !
and later, I will reinstall and test the non docker environment.
thanks.

**Closed as completed** 2020-02-14 18:17 UTC
