### ISSUE TITLE
can not stop job

### ISSUE THREAD

**Issue by javacodeofmy** [HiromuHota/pentaho-kettle#167] opened 2019-07-17 05:32 UTC
## Expected Behavior
When the job stops, the transformation stops.
## Actual Behavior
Hello, the version I used is 8.2.0.0-342. At present, I have encountered problems in the process of using it. I use a database-based resource library. After defining the transformation and job, when performing repeated jobs, when stopping the job, the transformation is still in progress and can not stop.

**Comment by HiromuHota** [comment] 2019-07-17 16:45
Thank you so much for reporting an issue!
Can you attach kjb/ktr files that can reproduce this issue?

**Comment by javacodeofmy** [comment] 2019-07-18 01:38
Yesterday I tested again, and found that the reason for the bug is that after defining the job that is executed repeatedly, such as every 10 seconds, the stop button is clickable without closing the job TAB, which can stop the job and the corresponding transition is also stopped.However, if the job is opened after closing the current job TAB without stopping the job, and the stop button is in the gray non-clickable state, the job task started before cannot be stopped, and the transition is still executed every 10 seconds, which cannot be stopped.

**Comment by HiromuHota** [comment] 2019-07-18 01:44
Does this happen on Spoon?

**Comment by javacodeofmy** [comment] 2019-07-18 01:46
I haven't tested the spoon of cs, I will test it and give you feedback.

**Comment by javacodeofmy** [comment] 2019-07-18 02:15
Yes, the same for spoon

**Comment by HiromuHota** [comment] 2019-07-18 17:31
As this happens on Spoon too hence it is not a bug of webSpoon, I'm afraid that I won't fix it.
You could find a similar issue at https://jira.pentaho.com, or report one if it's not been reported yet.

**Closed by HiromuHota** 2019-07-18 17:31 UTC
Labels: wontfix
