### ISSUE TITLE
RFI : how to fix crash on tabbed interface

### ISSUE THREAD

**Issue by mattcasters** [HiromuHota/pentaho-kettle#119] opened 2018-10-02 12:23 UTC
I get an error when my new perspective uses a TabFolder:

https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/issues/45

I would love any tips on how to debug and fix this.  I didn't see any loggin on the server.

**Comment by HiromuHota** [comment] 2018-10-02 16:52
If I remember correctly, I was suffering from this issue when I was developing the git plugin.
I had to take a workaround as you can see it [here](https://github.com/HiromuHota/pdi-git-plugin/blob/master/src/main/java/org/pentaho/di/git/spoon/GitPerspective.java#L80-L88).
My memo a year ago says 

> I suspect that this issue is a race-condition between the perspective rendering and its switching.

To debug such a race-condition, it was hard to debug. Basically I was doing trial and error hence not efficient way to debug.

I think the root cause comes from RAP/RWT. The RAP/RWT is less stable than SWT after all.
Let me quickly test the workaround for the neo4j plugin and see how it works.

**Comment by HiromuHota** [comment] 2018-10-02 17:10
The same workaround works on knowbi-pentaho-pdi-neo4j-output.

**Comment by HiromuHota** [comment] 2018-10-02 17:33
Resolved by HiromuHota/knowbi-pentaho-pdi-neo4j-output@72363f127bbf2db1edbafe5b90d9d127f51adfea.

**Closed by HiromuHota** 2018-10-02 17:33 UTC
