### ISSUE TITLE
Hope Interface language supports internationalization

### ISSUE THREAD

**Issue by gengzhengtao** [HiromuHota/pentaho-kettle#208] opened 2020-06-10 14:08 UTC
Hope Interface language supports internationalization
![image](https://user-images.githubusercontent.com/1639735/84278008-cfd3ce80-ab66-11ea-94ec-07b5eef266c9.png)

**Comment by HiromuHota** [comment] 2020-07-28 04:07
Duplicate of #158

**Closed as completed by HiromuHota** 2020-07-28 04:07 UTC
