### ISSUE TITLE
No suitable driver found for Webspoon 

### ISSUE THREAD

**Issue by gengzhizhen** [HiromuHota/pentaho-kettle#85] opened 2017-11-18 03:26 UTC
When run a webspoon job, get an error "No suitable driver found for jdbc:hive2://...". But with same configuration, run fine with pdi(kettle). 
Check the tomcat logs, it shoule be some ports are occupied . Will post the answer once I fix this problem.

Here are the whole configuration steps for webspoon.

1. Check the hadoop version which is CDH 5.8.2
2. Enter the container , modify  “active.hadoop.configuration” values to cdh510 in file /usr/local/tomcat/plugins/pentaho-big-data-plugin/plugin.properties
3. Remove the karaf cache and restart the container
4. Open webspoon and test connection which works fine.
5. And run the webspoon job, but get this error .

`09-Nov-2017 06:27:09.578 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
09-Nov-2017 06:27:09.579 SEVERE [main] org.apache.coyote.AbstractProtocol.init Failed to initialize end point associated with ProtocolHandler ["ajp-nio-8009"]
 java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:970)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:244)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:613)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:968)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:607)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:311)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:494`

[catalina.out.txt](https://github.com/HiromuHota/pentaho-kettle/files/1484325/catalina.out.txt)

**Comment by HiromuHota** [comment] 2017-11-20 21:18
Thanks for reporting.
I was able to reproduce this issue using version 0.7.1.13 and 0.8.0.13 of webSpoon but a different error.

```
2017/11/20 19:54:05 - Spoon - Save as...
2017/11/20 19:54:05 - Spoon - Save file as...
2017/11/20 19:54:24 - file:///root/.kettle/data/Untitled.ktr : Untitled - Dispatching started for transformation [file:///root/.kettle/data/Untitled.ktr : Untitled]
2017/11/20 19:54:24 - Table input.0 - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2017-11-20 07.36.10 by jenkins) : An error occurred, processing will be stopped: 
2017/11/20 19:54:24 - Table input.0 - Error occurred while trying to connect to the database
2017/11/20 19:54:24 - Table input.0 - 
2017/11/20 19:54:24 - Table input.0 - Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
2017/11/20 19:54:24 - Table input.0 - No suitable driver found for jdbc:hive2://172.18.0.2:10000/default
2017/11/20 19:54:24 - Table input.0 - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2017-11-20 07.36.10 by jenkins) : Error initializing step [Table input]
2017/11/20 19:54:24 - file:///root/.kettle/data/Untitled.ktr : Untitled - ERROR (version 8.0.0.0-28-13, build 8.0.0.0-28-13 from 2017-11-20 07.36.10 by jenkins) : Step [Table input.0] failed to initialize!
2017/11/20 19:54:24 - Table input.0 - Finished reading query, closing connection.
```

Here are my comments:
- I don't think the error `Address already in use` is causing this issue because I didn't get this error message.
- This is not so important, but your 2nd step can also be achieved by **Tools > Hadoop distribution** then select CDH.
- For the record, I was able to run the same transformation file in Spoon.

**Comment by HiromuHota** [comment] 2017-11-20 21:23
For the `Address already in use` error, please make sure that only one Tomcat instance is running at the same time.

**Comment by HiromuHota** [comment] 2017-11-27 19:37
Related issue:
https://github.com/pentaho/pentaho-kettle/pull/4525

I was able to reproduce this issue in Pan:
```
$ rm -rf system/karaf/caches/
$ ./pan.sh -file=/Users/hiromu/Downloads/Hive.ktr
2017/11/27 11:31:56 - Untitled - Data Set enabled? false
2017/11/27 11:31:57 - Table input.0 - linenr 50000
2017/11/27 11:31:58 - Table input.0 - linenr 100000
2017/11/27 11:31:59 - Table input.0 - linenr 150000
2017/11/27 11:32:00 - Table input.0 - linenr 200000
2017/11/27 11:32:01 - Table input.0 - linenr 250000
2017/11/27 11:32:02 - Table input.0 - linenr 300000
2017/11/27 11:32:03 - Table input.0 - linenr 350000
2017/11/27 11:32:04 - Table input.0 - linenr 400000
2017/11/27 11:32:05 - Table input.0 - Finished reading query, closing connection.
2017/11/27 11:32:05 - Table input.0 - Finished processing (I=445454, O=0, R=0, W=445454, U=0, E=0)
2017/11/27 11:32:05 - Pan - Finished!
2017/11/27 11:32:05 - Pan - Start=2017/11/27 11:31:55.675, Stop=2017/11/27 11:32:05.568
2017/11/27 11:32:05 - Pan - Processing ended after 9 seconds.
2017/11/27 11:32:05 - Untitled -  
2017/11/27 11:32:05 - Untitled - Step Table input.0 ended successfully, processed 445454 lines. ( 49494 lines/s)
$ ./pan.sh -file=/Users/hiromu/Downloads/Hive.ktr
2017/11/27 11:32:15 - Pan - Start of run.
2017/11/27 11:32:15 - Untitled - Dispatching started for transformation [Untitled]
2017/11/27 11:32:15 - Table input.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : An error occurred, processing will be stopped: 
2017/11/27 11:32:15 - Table input.0 - Error occurred while trying to connect to the database
2017/11/27 11:32:15 - Table input.0 - 
2017/11/27 11:32:15 - Table input.0 - Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
2017/11/27 11:32:15 - Table input.0 - No suitable driver found for jdbc:hive2://localhost:10000/default
2017/11/27 11:32:15 - Table input.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Error initializing step [Table input]
2017/11/27 11:32:15 - Untitled - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Step [Table input.0] failed to initialize!
2017/11/27 11:32:15 - Table input.0 - Finished reading query, closing connection.
```

**Comment by HiromuHota** [comment] 2017-11-27 19:38
Another related issue:
https://forums.pentaho.com/showthread.php?225558-Spoon-can-connect-ot-hive-but-kitchen-cannot

**Comment by HiromuHota** [comment] 2017-11-27 23:21
Resolved by https://github.com/HiromuHota/big-data-plugin/commit/98b988fcaf0f7f2585a4491c4a994355f07dd872

The root cause of this issue was that `jdbcUrl.getNamedCluster()` in https://github.com/pentaho/big-data-plugin/blob/8.0.0.0-R/impl/shim/hive/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriver.java#L70 ultimately calls Spoon.getInstance(), which invokes "Invalid thread access" when accessed from non-UI thread.
Thus, I commented-out the part in https://github.com/HiromuHota/big-data-plugin/commit/98b988fcaf0f7f2585a4491c4a994355f07dd872

As far as I investigated, this issue has nothing to do with https://github.com/pentaho/pentaho-kettle/pull/4525 and https://forums.pentaho.com/showthread.php?225558-Spoon-can-connect-ot-hive-but-kitchen-cannot.
Looks like these issues have a race-condition between HiveDriver's registration and its use. So it is hard to reproduce.

**Closed by HiromuHota** 2017-11-27 23:21 UTC

**Comment by HiromuHota** [comment] 2017-11-29 01:13
Reworked by https://github.com/HiromuHota/pentaho-osgi-bundles/commit/bc689ff0afa94a96917e7b8278f7ac1d2fac3b6c.
(Reverted https://github.com/HiromuHota/big-data-plugin/commit/98b988fcaf0f7f2585a4491c4a994355f07dd872 by https://github.com/HiromuHota/big-data-plugin/commit/ca1736f00823201ea9242db0575fe3a75ad67e4b).

**Comment by HiromuHota** [comment] 2017-11-29 22:13
For the record, this issue happened for Connection Type of "Impala", but already resolved.

**Comment by kiakaku** [comment] 2018-08-10 08:17
hi HiromuHota
I'm still get this error in 8.1 with

**Comment by HiromuHota** [comment] 2018-08-12 04:28
Today I checked with the latest release, i.e., 0.8.1.16 and found no error when reading a table from Hive.
@kiakaku, does your error happen on Spoon too?

![screen shot 2018-08-11 at 9 26 58 pm](https://user-images.githubusercontent.com/20668349/43998577-5793123c-9dad-11e8-979e-0b08256ece5c.png)

**Comment by kiakaku** [comment] 2018-08-13 04:45
hi @HiromuHota 

i'm getting error when i run Spoon in CentOS 7 with cdh514
But when i run in Window no error was found

**Comment by HiromuHota** [comment] 2018-08-13 18:40
Strange. Seems like it depends on the environment.
Can you paste the error message you've on webSpoon and the one on Spoon?

**Comment by kiakaku** [comment] 2018-08-14 02:47
hi

In the first time with Spoon everything is OK
but in the second times (without delete `/system/karaf/caches/` )
![image](https://user-images.githubusercontent.com/12557304/44068964-d933316e-9fa6-11e8-9c05-158e2fae3288.png)


I don't want delete `/system/karaf/caches/` because i want run multi job
