### ISSUE TITLE
 I could not connect to a repository

### ISSUE THREAD

**Issue by eliasbrito** [HiromuHota/pentaho-kettle#50] opened 2017-05-15 14:19 UTC
In Pentaho 7, the connection to the repository has been removed from the Tools> Repository> Connect menu. Now this option is in the upper right corner of the screen. I could not find any of the options on Spoon Web. Am I doing something wrong? Or is it really a bug for version 7?

**Comment by HiromuHota** [comment] 2017-05-15 18:58
From 7.0, the repository is provided as a plugin, meaning webSpoon should be deployed with plugins.
How did you deploy webSpoon?
- If it was deployed as a Docker container, please use the image "with plugins" (tag: latest-full).
- If it was deployed to (bare) Tomcat, download and unzip pdi-ce-7.0.0.0-25.zip, then copy the system and plugins folders to tomcat/system and tomcat/plugins, respectively.(https://github.com/HiromuHota/pentaho-kettle#deploy-to-bare-tomcat)
- If it was deployed to Pentaho server, deploying webSpoon with plugins does not work, hence is not currently supported.

**Comment by marcellobs** [comment] 2017-06-06 13:27
I has deployed webSpoon to Tomcat with Pentaho CE 7.1.0.0-12, i can configure connection to Repository but when i try to connect get message erro: login failure, but if i try to connect with spoon i can connect normaly.
I did copy plugins repositories-plugin-core-7.1.0.0-12.jar and repositories-plugin-core-7.1.0.0-12-source.jar to system/karaf/system/org/pentaho/repositories-plugin-core/7.1.0.0-12/ and others, like the recomendation on https://github.com/HiromuHota/pentaho-kettle#plugins, if i doesnt this, webSpoon can't get work correctly the Repositorie connection. 

Here the steps i did:

 - Download spoon.war https://github.com/HiromuHota/pentaho-kettle/releases/download/webspoon%2F0.7.1.9/spoon.war
 - Download and unzip apache-tomcat-9.0.0.M21
 - Copy spoon.war to webapps/ in apache-tomcat root directory
 - Copy plugins and system from pdi-ce-71.0.0-12 to apache-tomcat root directory
 - Copy pdi-platform-utils-plugin, big-data-plugin, repositories-plugin for determinated location, only repositories-plugin is diferent becouse of Pentaho CE.
 - Copy JDBCs to apache-tomcat/lib
 - Start apache-tomcat

**Comment by HiromuHota** [comment] 2017-06-06 21:49
Hi @marcellobs,
Thank for reporting.

I was able to reproduce the issue with webSpoon/0.7.1.9, so nothing wrong with your configurations.
I'm currently trying to figure out what is wrong.
In the meantime, you can try with webSpoon/0.7.0.9, which I tested again but didn't find this issue.

**Comment by HiromuHota** [comment] 2017-06-07 17:54
I fixed the issue by 71b441c0307cd112682e562832daf2099a8fdf76.
This was caused by the fact the **repositories-plugin** has changed the way how it works in 7.1.
You can build a spoon.war yourself using the latest commit, otherwise please wait for the next release.

**Comment by HiromuHota** [comment] 2017-09-06 00:40
Close this issue until it should be re-opened.

**Closed by HiromuHota** 2017-09-06 00:40 UTC
Labels: bug, question
